# Generated by Django 5.0.2 on 2024-02-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0007_remove_appointment_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
